name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build
      run:  npm install
    - name: Install modules
      run: |
        sudo npm install -g eslint
    - run: eslint index.js --ext .js,.jsx,.ts,.tsx